name: CI
on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [develop, master]
    
jobs:
  jpo-sdw-depositor:
    runs-on: ubuntu-latest
    container:
      # Use an image that matches the JDK version used in your Dockerfile as closely as possible
      image: eclipse-temurin:21-jdk-alpine
      options: --user root
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6 
      - name: Build and test with JaCoCo coverage
        run: |
          cd $GITHUB_WORKSPACE
          mvn -e -X clean org.jacoco:jacoco-maven-plugin:prepare-agent package
          mvn -e -X clean org.jacoco:jacoco-maven-plugin:report package
    
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./target/site/jacoco/jacoco.xml 

      - name: File type finder action
        id: ftf
        uses: ab185508/file-type-finder@main
        with:      
            path: "$GITHUB_WORKSPACE"
            type: "jacoco.xml"
          
  sonar:
    needs: [jpo-sdw-depositor]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   
      - name: Download JaCoCo Report
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
        
      - name: Setup SonarScanner
        uses: warchant/setup-sonar-scanner@v7
      - name: Generate sonar properties file
        run: |
          cat <<EOF > /tmp/sonar-scanner.properties
          sonar.host.url=https://sonarcloud.io
          sonar.coverage.jacoco.xmlReportPaths=/home/runner/work/jpo-sdw-depositor/jpo-sdw-depositor/home/runner/work/jpo-sdw-depositor/jpo-sdw-depositor/target/site/jacoco/jacoco.xml
          sonar.java.binaries=home/runner/work/jpo-sdw-depositor/jpo-sdw-depositor/target
          sonar.projectName=jpo-sdw-depositor
          sonar.projectKey=usdot-jpo-ode_jpo-sdw-depositor
          sonar.organization=usdot-jpo-ode
          jpo-sdw-depositor.sonar.projectBaseDir=home/runner/work/jpo-sdw-depositor/jpo-sdw-depositor
          jpo-sdw-depositor.sonar.sources=src
          jpo-sdw-depositor.sonar.tests=src/test
          jpo-sdw-depositor.sonar.test.inclusions=src/test/**
          EOF
      - name: Run SonarScanner
        uses: usdot-fhwa-stol/actions/sonar-scanner@main
        with:
          sonar-properties-path: /tmp/sonar-scanner.properties
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          working-dir: $GITHUB_WORKSPACE
